# Generated by Django 5.2.15 on 2026-06-13 03:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_day_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
