# Generated by Django 5.2.15 on 2026-06-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_event_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='day',
            field=models.IntegerField(default=1),
        ),
    ]
