# Generated by Django 5.2.15 on 2026-06-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='effect_type',
            field=models.CharField(default='sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=100),
        ),
    ]
