# Generated by Django 5.2.15 on 2026-06-13 04:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_event_effect_type_alter_player_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_event_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
