# Generated by Django 5.2.15 on 2026-06-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_last_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unlock_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='unlock_shop_level',
            field=models.IntegerField(default=1),
        ),
    ]
