# Generated by Django 5.2.15 on 2026-06-13 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_product_unlock_level_product_unlock_shop_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_sell_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
