# Generated by Django 5.2.15 on 2026-06-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_player_last_sell_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='level',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='upgrade_cost',
        ),
    ]
