# Generated by Django 5.2.15 on 2026-06-13 05:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_shop_level_remove_shop_upgrade_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_exp_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
