# Generated by Django 5.2.15 on 2026-06-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_player_last_exp_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='last_day_update',
            new_name='last_update',
        ),
        migrations.RemoveField(
            model_name='player',
            name='day',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_event_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_exp_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_sell_time',
        ),
    ]
