# Generated by Django 5.2.15 on 2026-06-13 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_rename_last_day_update_player_last_update_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='last_update',
            new_name='last_day_update',
        ),
        migrations.AddField(
            model_name='player',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='last_event_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='last_tick',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
