# Generated by Django 5.2.15 on 2026-06-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_rename_last_update_player_last_day_update_player_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shop',
            name='upgrade_cost',
            field=models.IntegerField(default=1000),
        ),
    ]
