# Generated by Django 5.2.15 on 2026-06-16 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_shop_level_shop_upgrade_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='last_day_update',
            new_name='phase_start',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_event_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_tick',
        ),
        migrations.AddField(
            model_name='player',
            name='phase',
            field=models.CharField(default='buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=1000),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('reward', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.product')),
            ],
        ),
    ]
