# Generated by Django 5.2.15 on 2026-06-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_rename_last_day_update_player_phase_start_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell_per_min',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unlock_shop_level',
        ),
        migrations.AddField(
            model_name='player',
            name='reputation',
            field=models.IntegerField(default=100),
        ),
    ]
