# Generated by Django 5.2.15 on 2026-06-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_delete_shop_remove_product_sell_per_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='匿名', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='orders/'),
        ),
    ]
