# Generated by Django 5.2.15 on 2026-06-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_order_customer_name_order_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='capacity',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='inventory',
            field=models.JSONField(default=dict),
        ),
    ]
