# Generated by Django 5.2.15 on 2026-06-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_player_capacity_player_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='debug_mode',
            field=models.BooleanField(default=False),
        ),
    ]
