# Generated by Django 5.2.15 on 2026-06-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_player_debug_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='playerachievement',
            name='unlock_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='achievement',
            name='condition',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='event',
            name='effect_type',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
