# Generated by Django 5.2.15 on 2026-06-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_remove_achievement_description_remove_event_effect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='capacity',
        ),
    ]
