# Generated by Django 5.2.15 on 2026-06-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_remove_player_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_profit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_sales',
            field=models.IntegerField(default=0),
        ),
    ]
