# Generated by Django 5.2.15 on 2026-06-20 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_player_total_orders_player_total_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
