# Generated by Django 5.2.15 on 2026-06-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_order_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='player',
        ),
    ]
