# Generated by Django 5.2.15 on 2026-06-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_remove_order_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='images/default.png', max_length=100),
        ),
    ]
