# Generated by Django 5.2.15 on 2026-06-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tutorial_done',
            field=models.BooleanField(default=False),
        ),
    ]
