# Generated by Django 5.2.15 on 2026-06-21 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_player_tutorial_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
            preserve_default=False,
        ),
    ]
